import './globals.css';
import { Inter, Montserrat } from 'next/font/google';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['200', '400', '600', '900'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="w-full h-screen overflow-y-auto bg-dark2">
                    <Navbar />
                    <main className="max-w-[1200px] p-2 mx-auto flex">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
